nama: Development User

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
---
spring:
    profiles: heroku
eureka:
    instance:
        hostname: belajar-springcloud-catalog.herokuapp.com