server:
    port: 8888

# Harusnya diset sebagai environment variabel ENCRYPT_KEY
# encrypt:
#    key: inisymmetrickeyrahasiasekali

spring:
    jackson:
        serialization:
            indent_output: true
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/endymuhardin/belajar-springcloud.git
                    searchPaths: 'config, config/{application}'
                    cloneOnStart: true
                    basedir: 'target/config'
